### ISSUE TITLE
怎么没人使用啊 这么好的组件

### ISSUE THREAD

**Issue by wwyn** [Chaunjie/kai-ui#1]

**Comment by Chaunjie** [comment]
已经有使用的案例了，希望大家能多提意见

**Comment by zwmmm** [comment]
我还没正式开始用,不过准备用这个组件库写一个小程序,目前发现有的组件传参很没有必要啊

**Comment by Chaunjie** [comment]
你可以给我列出来吗，有问题就有成长的空间

**Comment by zwmmm** [comment]
![image](https://user-images.githubusercontent.com/30194521/44575951-f07b3a80-a7bf-11e8-9978-77690daad36f.png)
就比如这个 linkType 和 iconType 我不知道您这么设置有没有其他用途,至少在我目前使用中 完全可以去判断 link 这个值是否传了来判断需不需要跳转

**Comment by sundew26** [comment]
linktype：
0. 无需跳转
1. 跳转
这个参数是为了实现有些列表没有右侧箭头，却需要跳转的情况。

icontype：
0. 表示不传左侧小图标 
1. 表示左侧小图标是iconfont格式 
2. 表示是图片src格式
这个参数是配合icontext使用的，用户可以传入不同种的图片或者iconfont图标

link：页面需要跳转到哪个页面

可能这样设计有点啰嗦，有好的建议欢迎提出来哦。
