### ISSUE TITLE
关于wepy的popup的位置显示bug异常的反馈与吐槽

### ISSUE THREAD

**Issue by wangyequn** [Chaunjie/kai-ui#14]
### 问题反馈
由于将`export default class Popup extends wepy.component`写成`export default class Popup extends wepy.page`导致组件属性传值不能正常使用
### 吐槽
在使用wepy版本的popup的过程中,发现怎么设置显示位置也不好使,然后就开始看您的源码,感觉是不是源码出啥子问题了,怎么看怎么没问题,甚至把源码删减到只有一个props,只显示一行hello world还是不行,反复的比对是不是单词拼错了,一个单词一个单词的赋值粘贴,依旧没有发现任何问题,可是位置信息就是显示不过来,都已经准备放弃了,打算将四个方向设置为四个组件,设置默认值;突然一个单词映入我的眼帘
![image](https://user-images.githubusercontent.com/29917566/47663192-6d1f0080-dbd7-11e8-8803-44046c326486.png)
微笑,生活很美好

**Comment by stardew** [comment]
很抱歉，给您带来的不便，接受批评。
更加感谢您指出问题，以后会更加细心。
问题已修复，本周会再上一个版本。

**Comment by sundew26** [comment]
版本已更新    如有 问题  欢迎反馈 https://chaunjie.github.io/kui/dist/#/wepy/popup

**Comment by dtboy1995** [comment]
周二clone项目的时候依然有个这个问题。不查issue的时候快疯了。。。。原来是这个错。。

**Comment by Chaunjie** [comment]
@dtboy1995 npm包是没有问题的，因为clone默认是master分支，之前没有合并，现在clone没有问题

**Comment by dtboy1995** [comment]
@Chaunjie  谢谢，辛苦
