### ISSUE TITLE
嗨，我想问一下如何在cell组件里面，使用tap的函数呢？

### ISSUE THREAD

**Issue by watsonhaw** [Chaunjie/kai-ui#15]
![image](https://user-images.githubusercontent.com/1267552/47771124-0277dd00-dd1d-11e8-8574-b65f029d285b.png)
因为在文档里面只可以做跳转，但是，我如果想客户点击一个cell做一个函数操作，我可以怎么操作呢？
谢谢git主大大。

**Comment by sundew26** [comment]
文档很久没更新了，请看新版文档。里面有个回调事件item-tap
https://chaunjie.github.io/kui/dist/#/wepy/cell

**Comment by watsonhaw** [comment]
谢谢@stardew516大大
