### ISSUE TITLE
压根找不到组件啊

### ISSUE THREAD

**Issue by fangdong116** [Chaunjie/kai-ui#16]
[Error] 找不到组件：kai-ui/Panel
![image](https://user-images.githubusercontent.com/12489108/48109201-6cdecf00-e281-11e8-8d40-e0a2fec98771.png)

**Comment by sundew26** [comment]
请问是所有的组件都找不到  还是只有这个组件找不到   
有根据文档载入组件库吗https://chaunjie.github.io/kui/dist/#/wepy/start

**Comment by dtboy1995** [comment]
同样的问题
wepy版本`1.73`
kai-ui 版本 `1.2.4`
求解

**Comment by sundew26** [comment]
> 同样的问题
> wepy版本`1.73`
> kai-ui 版本 `1.2.4`
> 求解

你好 我刚刚 用wepy1.7.3 和 kai-ui 1.2.4 新建了个项目，引入panel是可以用的。就是按照文档来的，不知道你哪步操作不对，方便提供具体使用细节吗？

![1](https://user-images.githubusercontent.com/15061629/48752190-05823f80-ecc3-11e8-80d6-0d76457bdbcc.jpeg)
![11](https://user-images.githubusercontent.com/15061629/48752206-0d41e400-ecc3-11e8-90f2-69e09c9fe845.jpeg)
![111](https://user-images.githubusercontent.com/15061629/48752217-16cb4c00-ecc3-11e8-967d-e2f4c4f0ab2b.jpeg)
![11111](https://user-images.githubusercontent.com/15061629/48752225-1d59c380-ecc3-11e8-8d46-50b1d349b9cf.jpeg)

**Comment by dtboy1995** [comment]
我和第一个哥们的问题一样，@stardew516，谢谢回复，我晚点再测试一遍，如果能复现的话整个gif给您

**Comment by dtboy1995** [comment]
@stardew516 以下是重现
如果怀疑是shell问题我在**gitbash**和**powershell**都跑了
![error screen snap](https://wenan-public.oss-cn-beijing.aliyuncs.com/error.gif)

issue 中的文件有大小限制
这是原地址https://wenan-public.oss-cn-beijing.aliyuncs.com/error.gif

**Comment by Chaunjie** [comment]
@dtboy1995 是wepy编译问题你看下这个能不能解决你的问题[点击这里](https://github.com/Tencent/wepy/issues/455)

**Comment by Chaunjie** [comment]
@dtboy1995 你其他的组件这样引用有问题吗？

**Comment by dtboy1995** [comment]
@Chaunjie 感谢回复，其他组件我没试，当时第一步都过不去

**Comment by dtboy1995** [comment]
稍等，我去awesome上去找个别的组件试试

**Comment by dtboy1995** [comment]
@Chaunjie 刚试了`wepy-com-charts`没问题

**Comment by Chaunjie** [comment]
@dtboy1995 组件编译模式和组件库的不一样，单个组件入口时package.json中的main,组件库是wepy字段，你可以对照着kai-ui改下试试，然后你尝试下kai-ui的其它组件看看，如果其它组件可以编译就panel不能的话就应该是panel的问题

**Comment by dtboy1995** [comment]
```log
[Error] 找不到组件：kai-ui/Cell
[Error] 找不到组件：kai-ui/CellGroup
```
总之辛苦作者了，先不弄了

**Comment by Chaunjie** [comment]
@dtboy1995 你现在尝试把wepy-com-charts组件main置为''，并且把它添加到wepy字段内试试，应该是wepy编译的问题

**Comment by dtboy1995** [comment]
那就等着wepy2.0吧，谢谢了

**Comment by Chaunjie** [comment]
wepy2.0版本还在内测，目前你还是拷贝出来使用吧，虽然不是很方便
