### ISSUE TITLE
https://github.com/Chaunjie/kai-ui/issues/16#issue-378129452

### ISSUE THREAD

**Issue by dtboy1995** [Chaunjie/kai-ui#17]
无解啊亲爱的作者。。

**Comment by Chaunjie** [comment]
@dtboy1995 没有复现你的问题，环境与你一致，你能提供一份有问题的代码给我吗，方便定位下问题

**Comment by dtboy1995** [comment]
@Chaunjie 感谢回复，我就是按照您的文档 安装完引入的，现在直接下载你的项目直接使用了。。

**Comment by dtboy1995** [comment]
现在已经没有我的代码了，哈哈。我是直接clone您的项目，当脚手架去改了

**Comment by Chaunjie** [comment]
我本地测试过的确没有发现问题，可能需要重新跑一遍吧
