### ISSUE TITLE
swipeout 删除选中的数据时，自动展开下一个？如图

### ISSUE THREAD

**Issue by 531431988** [Chaunjie/kai-ui#19]
删除前
![image](https://user-images.githubusercontent.com/8703951/49868935-cff7ee80-fe49-11e8-9547-e4a94628361e.png)

删除后
![image](https://user-images.githubusercontent.com/8703951/49868957-e56d1880-fe49-11e8-85e5-3485d1f4ac37.png)

为何后面的自动展开操作按钮？怎么取消展开操作

**Comment by Chaunjie** [comment]
@531431988 用的是wepy版本还是原生的版本？

**Comment by wppeng** [comment]
@531431988  复现了你的问题，正在解决中。先提供个临时解决方案：可以先清空下数据，然后再更新，类似这样：
```bash
    this.setData({
      items: []
    }, () => {
      let newArr = [...items]
      newArr.splice(index, 1)
      this.setData({
        items: newArr
      })
    })
```

**Comment by wppeng** [comment]
@531431988 另外一个比较好的解决方案：
swipeout 组件内加个 reset 方法，先手动加一下，下个版本会更新上去：
```bash
   reset () {
      return new Promise((resolve, reject) => {
        this.setData({
          left: 0,
          startX: ''
        }, () => {
          resolve()
        })
      })
    }
```
然后页面上，先调用组件的 reset 方法，再更新数组：
```bash
    const swipeCtx = this.selectComponent('#swipe-' + index)
    swipeCtx.reset().then(res => {
      const newArr = [...items]
      newArr.splice(index, 1)
      this.setData({
        items: newArr
      })
    })
```

**Comment by Chaunjie** [comment]
@531431988 该问题是小程序组件bug导致的，你可以使用上述两个方案解决

**Comment by 531431988** [comment]
好的，感谢

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/49991322-af4fa600-ffbb-11e8-8c5b-0ecb9ecf16dc.png)

![image](https://user-images.githubusercontent.com/8703951/49991312-a65ed480-ffbb-11e8-981b-e5944f572d19.png)
![image](https://user-images.githubusercontent.com/8703951/49991327-b5de1d80-ffbb-11e8-924a-1681814d07d7.png)
 求个demo

**Comment by Chaunjie** [comment]
@531431988 不要放到onLoad函数内调用该函数，你要在你执行了删除之后在删除数组之前执行该逻辑

**Comment by Chaunjie** [comment]
@531431988 给你提供一个例子
page-js
![image](https://user-images.githubusercontent.com/12093709/49992142-25eda300-ffbe-11e8-8209-922c6e818a66.png)
page-wxml
![image](https://user-images.githubusercontent.com/12093709/49992166-36058280-ffbe-11e8-9cfc-6bb5ccd23386.png)
找到kai-ui/swipeout/index.js新增一个方法
![image](https://user-images.githubusercontent.com/12093709/49992219-62b99a00-ffbe-11e8-8f7b-07988c90838b.png)

**Comment by 531431988** [comment]
我用wepy框架写的，一直取不到ID

**Comment by Chaunjie** [comment]
@531431988 看看这个能不能解决你的问题[链接](https://github.com/Tencent/wepy/issues/1216)

**Comment by 531431988** [comment]
试了无数次，依然取不到
也看是文档说需要usingComponents引入，确实也是这样引入的
this.$wxpage.selectComponent(id or class) 在wepy里面一直都取不到

**Comment by Chaunjie** [comment]
@531431988 可能你的wepy版本不兼容usingComponents吧，关于这个我没法帮到你，你可以去wepy社区寻求下帮助

**Comment by 531431988** [comment]
好的，谢谢大佬
