### ISSUE TITLE
tab 动态添加后的标签页无法滚动

### ISSUE THREAD

**Issue by 531431988** [Chaunjie/kai-ui#21]
选中状态的效果位置不正确，动态添加的会报width找不到？求指点

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/50155693-b5b98700-0307-11e9-9b7d-5be237db4e11.png)

**Comment by 531431988** [comment]
大概意思是，tab有个scroll支持横向滚动，当点击到边缘时会自动往前或后滚动出下一个选项，但当TAB标签是动态增删选项时，点击失效，滚动也失效

**Comment by 531431988** [comment]
固定5个时，操作正常
![image](https://user-images.githubusercontent.com/8703951/50193484-cc94c380-0371-11e9-81f7-04c7e9c88289.png)

动态添加标签
![image](https://user-images.githubusercontent.com/8703951/50193507-ddddd000-0371-11e9-9a1c-c8fa0459ef28.png)

错位
![image](https://user-images.githubusercontent.com/8703951/50193532-f0f0a000-0371-11e9-8848-b8615bd078f2.png)

源码修改
![image](https://user-images.githubusercontent.com/8703951/50193553-08c82400-0372-11e9-950a-01bc22f5fa68.png)

**Comment by Chaunjie** [comment]
@531431988 动态新增的时候需要重制数据
`this.$invoke('tab', 'doInitTabData', this.tabData)`

**Comment by 531431988** [comment]
this.$invoke('tab-scroll', 'doInitTabData', Object.assign(this.tabData, {
        list: [...this.mineTabData, ...this.otherTabData]
      }))
绘过，一样啊，大佬来个wepy例子看看？

**Comment by Chaunjie** [comment]
@531431988 你整理一个有问题的demo发给我排查下

**Comment by 531431988** [comment]
[demo.zip](https://github.com/Chaunjie/kai-ui/files/2693033/demo.zip)
WEPY版，大佬求指点

**Comment by Chaunjie** [comment]
![image](https://user-images.githubusercontent.com/12093709/50196350-cefd1a80-037d-11e9-8bde-39dc208f6a9b.png)
不是好的吗？

**Comment by 531431988** [comment]
大佬有Q？不可能啊，我发你前还测试了

**Comment by 531431988** [comment]
打开页面，先切换到第5个，在添加所有标签，关闭后，在试一下切换？

**Comment by 531431988** [comment]
刚已经测试，你那个是直接打开页面后就进行了添加，没有切换操作，如果先切换在添加，就出问题了

**Comment by Chaunjie** [comment]
@531431988 看到问题了，动态操作的时候因为容器宽度变化了，导致计算的位置有问题，如果动态操作之后重置为第一个选择就没有问题，这个bug计划下一个版本修复

**Comment by 531431988** [comment]
你的意思是，添加完后，手动设置选中第一个？

**Comment by Chaunjie** [comment]
对的，你试下，看看能不能满足你的需求，不能满足的话我今晚给你一个补丁看看

**Comment by 531431988** [comment]
坐等大佬更新

**Comment by Chaunjie** [comment]
[demo-2.zip](https://github.com/Chaunjie/kai-ui/files/2693725/demo-2.zip)
@531431988 给你打了一个补丁包，参考tab组件，wepy组件库之后维护的次数应该不多，可以直接使用kai-ui原生组件库

**Comment by 531431988** [comment]
感谢大佬，swipeout这个组件的滚动展开隐藏一直没能解决，不知道有没有什么办法

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/50217210-0b069e80-03c3-11e9-85fc-3b36913f70cb.png)
还是存在一些问题， 添加 一个，在删除一个就报错了

**Comment by Chaunjie** [comment]
@531431988 删除执行doUpdateData没有这个方法啊，你需要按照新增的方法执行

**Comment by Chaunjie** [comment]
swipe-out的代码贴给我看看

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/50266966-a437c280-0460-11e9-91fc-46d704c38a5d.png)
![image](https://user-images.githubusercontent.com/8703951/50266987-b31e7500-0460-11e9-9154-73772426aaed.png)
tab.wpy里面并没有doUpdateData方法呀

**Comment by Chaunjie** [comment]
删除的我没有帮你写，你重新initData一次

**Comment by 531431988** [comment]
[swipeout.zip](https://github.com/Chaunjie/kai-ui/files/2697654/swipeout.zip)
 删除第一个，下一个自动打开？
TBA已经修复好，感谢大佬

**Comment by Chaunjie** [comment]
@531431988 不上传了，截图给你，自己完成
![image](https://user-images.githubusercontent.com/12093709/50269368-08f71b00-0469-11e9-9290-c6d267da4e7c.png)
组件新增一个方法
![image](https://user-images.githubusercontent.com/12093709/50269383-12808300-0469-11e9-8d33-9c5d582b12ed.png)

**Comment by 531431988** [comment]
已经解决，感谢大佬，在多问一下，同时展开一个是无法办到的吗？现在可以同时展开多个

**Comment by Chaunjie** [comment]
组件与组件之间是没有联系的，所以并没有必要这么做

**Comment by Chaunjie** [comment]
@531431988 wepy框架组件bug比较多，所以kai-ui库wepy版本之后会很少维护，有时间的话参考下我写的小程序框架[wexp-cli](https://github.com/Chaunjie/wexp-cli)可以有效的解决这些问题，同样支持原生组件引入。

**Comment by 531431988** [comment]
好的
