### ISSUE TITLE
wepy中组件引用的错误

### ISSUE THREAD

**Issue by route-nice** [Chaunjie/kai-ui#25]
[按照文档引入出错，代码如下](https://chaunjie.github.io/kui/dist/#/wepy/start)
`<template>
    <k-panel>使用kai-ui组件库开始</k-panel>
</template>
<script>
    import Panel from 'kai-ui/Panel'

    components = {
        'k-panel': Panel
    }
</script>`
报错如下
` ERR! dependence   Can not import a wepy component, please use "usingComponents" to declear a component
[15:40:23] ERR! dependence File:
[15:40:23] ERR! dependence   E:\wspaces\vscode\myproj\node_modules\kai-ui\src\components\panel\index.wpy
[15:40:23] ERR! dependence Snapshot:
[15:40:23] ERR! dependence   3 | var _Panel = _interopRequireDefault(require("kai-ui/Panel"));
[15:40:23] ERR! dependence   4 | 
[15:40:23] ERR! dependence > 5 | function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
[15:40:23] ERR! dependence   6 | 
[15:40:23] ERR! dependence   7 | components = {
[15:40:23] ERR! dependence   8 |   'k-panel': _Panel["default"]`
@Chaunjie

**Comment by Chaunjie** [comment]
你好这个是wepy的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"route-nice"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 下午3:44
收件人:&nbsp;"Chaunjie/kai-ui"<kai-ui@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Chaunjie/kai-ui] wepy中组件引用的错误 (#25)





 
按照文档引入出错，代码如下
 `
 使用kai-ui组件库开始
 
 <script&gt;     import Panel from 'kai-ui/Panel'     components = {         'k-panel': Panel     } </script&gt;` 
报错如下
  ERR! dependence   Can not import a wepy component, please use "usingComponents" to declear a component [15:40:23] ERR! dependence File: [15:40:23] ERR! dependence   E:\wspaces\vscode\myproj\node_modules\kai-ui\src\components\panel\index.wpy [15:40:23] ERR! dependence Snapshot: [15:40:23] ERR! dependence   3 | var _Panel = _interopRequireDefault(require("kai-ui/Panel")); [15:40:23] ERR! dependence   4 |  [15:40:23] ERR! dependence &gt; 5 | function _interopRequireDefault(obj) { return obj &amp;&amp; obj.__esModule ? obj : { "default": obj }; } [15:40:23] ERR! dependence   6 |  [15:40:23] ERR! dependence   7 | components = { [15:40:23] ERR! dependence   8 |   'k-panel': _Panel["default"]

**Comment by Chaunjie** [comment]
你可以使用我们这边原生版本的组件，wepy框架有添加原生组件的支持
