### ISSUE TITLE
引入不成功

### ISSUE THREAD

**Issue by leeyoungae** [Chaunjie/kai-ui#3]
我是按照文档上 npm install 的
在app.wpy 引入，单纯css样式组件没有问题，但是引入js组件就报错了.
app.wpy
![image](https://user-images.githubusercontent.com/10704687/44707703-d7340000-aad7-11e8-825a-5917bc77dd6b.png)

page.wpy
![image](https://user-images.githubusercontent.com/10704687/44707733-f29f0b00-aad7-11e8-8ec0-3810f23203da.png)

error:
![image](https://user-images.githubusercontent.com/10704687/44708111-db145200-aad8-11e8-8c94-d008a7fa0ffa.png)

**Comment by Chaunjie** [comment]
wepy-cli版本^1.7.3才支持这么引入组件，低于这个版本的需要拷贝components文件到你自己的目录

**Comment by leeyoungae** [comment]
components 整个文件很大 ，700多K哦，小程序的空间很珍贵 T_T

**Comment by Chaunjie** [comment]
@leeyoungae 只有80+k吧，而且打包之后会压缩的
![image](https://user-images.githubusercontent.com/12093709/44708519-ecaa2980-aad9-11e8-85b2-af1e60073cdf.png)

**Comment by leeyoungae** [comment]
难道我的包有问题？

**Comment by Chaunjie** [comment]
@leeyoungae 你只需要把components拷贝出来就好了，其他的不用

**Comment by leeyoungae** [comment]
@Chaunjie  我现在只拷贝了components 改名了 “kaiui”
![image](https://user-images.githubusercontent.com/10704687/44710070-d2724a80-aadd-11e8-98c4-160554dfa8ee.png)
但是好像还是出错.
![image](https://user-images.githubusercontent.com/10704687/44710115-e7e77480-aadd-11e8-9fe3-42b7ed992129.png)
![image](https://user-images.githubusercontent.com/10704687/44710118-ed44bf00-aadd-11e8-9d78-8fe3c27fded4.png)

**Comment by Chaunjie** [comment]
能否把整个目录截图给我看下，并且把拷贝进去的组件库标出来

**Comment by leeyoungae** [comment]
src结构吗？
![image](https://user-images.githubusercontent.com/10704687/44710269-50ceec80-aade-11e8-9607-f02b8eb3c0a1.png)
![image](https://user-images.githubusercontent.com/10704687/44710286-59bfbe00-aade-11e8-9a93-4b2a9ba923b1.png)
![image](https://user-images.githubusercontent.com/10704687/44710297-60e6cc00-aade-11e8-8dee-c5068cea41b0.png)

**Comment by Chaunjie** [comment]
你把components拷贝到你自己项目重的components目录下试试，按照wepy官方推荐的做法来

**Comment by leeyoungae** [comment]
不要放二级目录上？

**Comment by Chaunjie** [comment]
对的

**Comment by leeyoungae** [comment]
编译过程中会有出错
![image](https://user-images.githubusercontent.com/10704687/44710974-eae36480-aadf-11e8-848a-e5f7bad1b6e0.png)

**Comment by Chaunjie** [comment]
你是怎么引入的？

**Comment by leeyoungae** [comment]
直接平铺 啊
![image](https://user-images.githubusercontent.com/10704687/44711234-7230d800-aae0-11e8-9350-577cdddb8115.png)

**Comment by Chaunjie** [comment]
这么引入会有问题？
![image](https://user-images.githubusercontent.com/12093709/44711222-6d6c2400-aae0-11e8-9d7f-b8568dbe1bb5.png)

**Comment by leeyoungae** [comment]
引入后编译有问题，我删除了components下了kai-ui组件文件夹/文件，就正常，没有出错

**Comment by Chaunjie** [comment]
你把less文件夹也拷贝到src目录下应该就没问题了

**Comment by leeyoungae** [comment]
![image](https://user-images.githubusercontent.com/10704687/44714270-7e6c6380-aae7-11e8-9fad-5afb01fafc24.png)
@Chaunjie

**Comment by leeyoungae** [comment]
![image](https://user-images.githubusercontent.com/10704687/44714308-9348f700-aae7-11e8-8679-2a00533fecd5.png)

**Comment by Chaunjie** [comment]
@leeyoungae 这个step组件没有屏蔽，step组件会在接下来版本添加上去，如果你用到上传组件的话可以把七牛的sdk补上去，用不到的话可以直接删掉，同样的step可以删掉，接下来我会完善下，谢谢指出问题

**Comment by Chaunjie** [comment]
@leeyoungae 你这个问题解决了吗，解决了我就关掉这个issue了

**Comment by leeyoungae** [comment]
还没有呢

**Comment by Chaunjie** [comment]
@leeyoungae 按照我给你提供的方案不能解决吗？
