### ISSUE TITLE
Cannot read property 'dir' of null

### ISSUE THREAD

**Issue by wangyequn** [Chaunjie/kai-ui#8]
wepy版本，在引入组件的时候报错：报错的内容为：
[Error] TypeError: Cannot read property 'dir' of null

**Comment by Chaunjie** [comment]
请问是引用哪个组件？

**Comment by watsonhaw** [comment]
![image](https://user-images.githubusercontent.com/1267552/46592097-28c9a480-caf2-11e8-9a9d-650bc678c8b0.png)
估计楼上的和我的是一样的，就是按照文档来的，我第一感觉就是引用的组件的路径是不对的。

**Comment by Chaunjie** [comment]
@wangyequn @watsonhaw 你们的wepy-cli是什么版本的？

**Comment by watsonhaw** [comment]
就是用了新版的wepy-cli，我用了相对路径也不行，有点懵了。
![image](https://user-images.githubusercontent.com/1267552/46592800-88c34980-caf8-11e8-88c8-88790bfaa803.png)

**Comment by Chaunjie** [comment]
告诉我下wepy-cli版本号@watsonhaw

**Comment by watsonhaw** [comment]
1.7.2，我把你的全部的组件放到wepy的compents里面，再看你demo里面的实例，终于可以出来了。
![image](https://user-images.githubusercontent.com/1267552/46594042-43f0e000-cb03-11e8-9168-b5fc12a508ba.png)

**Comment by Chaunjie** [comment]
@watsonhaw 需要1.7.3+版本才支持这么引用，低于这个版本的就把相应的文件拷贝出来用吧

**Comment by Chaunjie** [comment]
@wangyequn 你估计也是因为wepy-cli 版本的问题，可以把组件资源拷贝出来使用即可

**Comment by watsonhaw** [comment]
这，有1.7.3版本这么优秀了？，文档只有1.7.2啊，这也是醉了

**Comment by Chaunjie** [comment]
对的，1.7.3版本的确是支持这样的用法，你可以直接安装1.7.3版本试试

**Comment by watsonhaw** [comment]
收到，谢谢大大，感谢耐心回复

**Comment by Chaunjie** [comment]
不客气

**Comment by Licoy** [comment]
但是在1.7.3中这样引入照样报错`Cannot read property 'dir' of null`，我并没有将组件放在wepy的components内

**Comment by Licoy** [comment]
@Chaunjie

**Comment by Chaunjie** [comment]
@Licoy 方便截图吗？

**Comment by Licoy** [comment]
@Chaunjie ![QQ截图20181009120805.jpg](https://i.loli.net/2018/10/09/5bbc29b85b578.jpg)

**Comment by Chaunjie** [comment]
@Licoy 我们这边测试过1.7.3没有问题啊，你运行下wepy -v之后截图我看看

**Comment by Licoy** [comment]
```
G:\dev\project\yuekanshuwu\wechat-app>wepy -version
1.7.3
```

@Chaunjie  是这个么？

**Comment by Licoy** [comment]
```
G:\dev\project\wechat-app>wepy -version
1.7.3
```

@Chaunjie  是这个么？

**Comment by Chaunjie** [comment]
![image](https://user-images.githubusercontent.com/12093709/46647179-3d28a280-cbc1-11e8-8265-8cedbf803921.png)
我刚刚使用了下，并没有重现你说的问题

**Comment by Chaunjie** [comment]
@Licoy 能否提供下你的demo，我定位下是什么问题

**Comment by Licoy** [comment]
@Chaunjie demo地址： [腾讯微云](https://share.weiyun.com/5FOr0jH)

**Comment by Chaunjie** [comment]
@Licoy我按照你的包来操作没有问题啊，我本地wepy-cli 版本是1.7.3
![image](https://user-images.githubusercontent.com/12093709/46649925-6f400180-cbcd-11e8-805f-feb7235b0093.png)
![image](https://user-images.githubusercontent.com/12093709/46649970-8d0d6680-cbcd-11e8-9255-bc4ba5bc4d94.png)
![image](https://user-images.githubusercontent.com/12093709/46650008-ad3d2580-cbcd-11e8-9312-c310690d02e0.png)

**Comment by Licoy** [comment]
@Chaunjie 我的也是1.7.3的，但是就是要报这个错...很无奈
![QQ截图20181009141639.png](https://i.loli.net/2018/10/09/5bbc47de6438d.png)

**Comment by Chaunjie** [comment]
@Licoy 你重新开一个终端运行下试试，感觉太奇怪了

**Comment by Licoy** [comment]
@Chaunjie 还是一样的结果 我用的是我给你发的那个demo那一份，运行结果还是一样的。

![QQ截图20181009142411.png](https://i.loli.net/2018/10/09/5bbc4997e3699.png)

**Comment by Licoy** [comment]
@Chaunjie 我用npm卸载了wepy-cli，然后使用yarn安装了wepy-cli还是一样的结果，难道有系统环境的影响？我的是Windows，你的应该是Mac吧

**Comment by watsonhaw** [comment]
复制路径引用吧，这样引用有问题的话，我之前这样的处理好了。

**Comment by Chaunjie** [comment]
@Licoy 按照编译提示显示是第三方组件已经编译了，你看下dist目录下有没有这几个文件，错误提示是编译样式出的问题，可能你本地未装成功less模块

**Comment by Licoy** [comment]
我试试

**Comment by Licoy** [comment]
@Chaunjie 本地Less组件已经安装，在dist目录下也有文件，但是一直都是这个错误0.0

**Comment by Licoy** [comment]
@watsonhaw 直接复制出来有路径问题 貌似

**Comment by Chaunjie** [comment]
@Licoy 你的页面中样式尝试用引入less文件的形式试试，先把组件注释掉，看看是否报错

**Comment by Licoy** [comment]
@Chaunjie 是支持的，但是引入你的那个模块就不行

![3.png](https://i.loli.net/2018/10/09/5bbc509123d54.png)
![1.png](https://i.loli.net/2018/10/09/5bbc5091559b2.png)
![2.png](https://i.loli.net/2018/10/09/5bbc5091254a1.png)

**Comment by Chaunjie** [comment]
![image](https://user-images.githubusercontent.com/12093709/46654608-dcf32a00-cbdb-11e8-8140-edc844208a00.png)
看编译情况是都写入成功，你看下你的demo能运行起来吗？@Licoy

**Comment by Licoy** [comment]
@Chaunjie 运行起来没有效果

**Comment by Chaunjie** [comment]
@Licoy 是wepy-cli编译出现的问题，拷贝出来用吧

**Comment by Licoy** [comment]
@Chaunjie ...okay

**Comment by Chaunjie** [comment]
我本人近期也在开发另外一个类似原生写法的小程序框架[wexp](https://github.com/Chaunjie/wexp-cli)，有时间可以看看

**Comment by Licoy** [comment]
@Chaunjie ok

**Comment by hellohejinyu** [comment]
这个kai-ui在Windows下用简直就是灾难，MacOS一点问题没有。

**Comment by Chaunjie** [comment]
@elowes 组件库跟系统没什么关系，只跟编译wepy-cli有关系，如果wepy-cli在windows系统下有编译问题建议直接拷贝到项目用

**Comment by hellohejinyu** [comment]
是的，确实不是kai-ui的锅，我应该去wepy下面吐槽去的。看了一下wepy的源码，出了个临时patch方案。供大家参考。我本地项目已经可以正常在Windows下使用kai-ui了。
修改一下全局安装的wepy-cli中的util.js和compile-style.js两个文件的这几个地方就可以了。
![menu saveimg savepath20181127144856](https://user-images.githubusercontent.com/8766034/49063918-fb78b780-f253-11e8-9aca-a6d76409a2c3.jpg)
具体出错原因是因为wepy的程序员哥哥错误的使用path.sep来解析路径（例如：kai-ui/Panel），然后在Windows下path.sep的值是\，MacOS和Linux下是/。
![menu saveimg savepath20181127145352](https://user-images.githubusercontent.com/8766034/49064058-7b068680-f254-11e8-95de-bb1220167818.jpg)
祝大家用的开心，也祝kai-ui越来越好：）

**Comment by Chaunjie** [comment]
@elowes 建议你把这个贴给wepy开发者，可以为更多因为这个问题的人解惑。因为wepy的组件问题一直没有解决，我个人已经放弃wepy，转而开发自己的wexp

**Comment by hellohejinyu** [comment]
@Chaunjie 我一会儿提个 issue 给他们去，对 wepy 不太熟，我不好提 pr，修不修看他们自己了
